version: 2
updates:
  - package-ecosystem: "composer"
    # Raise pull requests to update vendored dependencies that are checked in to the repository
    vendor: true
    schedule:
      interval: "weekly"
